### ISSUE TITLE
Not working on Ubuntu. 

### ISSUE THREAD

**Issue by DrewWalsh** [fabiospampinato/vscode-open-in-browsers#1]
Not working on Ubuntu. Nothing happens, no errors.

**Comment by fabiospampinato** [comment]
Thanks for reporting the issue.

Do you have Chrome installed? Is it called exactly "Google Chrome"? If so you may try to put this in your settings: `"openInBrowsers.browser": "\"Google Chrome\""` and check if it works. If it does I think I know how to fix this.

**Comment by DrewWalsh** [comment]
Nope. Still does nothing.
Tested Default browser for Chrome as specified and a few other variants (Chrome, google-chrome) to be sure. Tried a few variants for Firefox as well (Firefox, Mozilla Firefox, Firefox Web Browser). Reloading VS Code  between each test of course.

**Comment by fabiospampinato** [comment]
Ok, thanks for the help. I'll fix this as soon as I get some free time.

**Comment by fabiospampinato** [comment]
The extension is actually working, it's just a matter of finding the proper names to use. 

For instance for opening Firefox you need to use "firefox", for Chromium "chromium". For some reasons I couldn't install Google Chrome so I don't know what you have to use for that, you may try with "google-chrome-stable", which is the name of the actual package.

Would you mind reconsidering your 1-star rating in the marketplace please?
