### ISSUE TITLE
Add `Open in...` to context menu

### ISSUE THREAD

**Issue by kanlukasz** [fabiospampinato/vscode-open-in-browsers#5]
Hello,

**Type:**
Future request:

**Description:**
I think it would be useful to add the features of your plugin to the context menu.
I mean, here in sidebar:
![obraz](https://user-images.githubusercontent.com/30685349/77531519-5b589000-6e93-11ea-942d-76a910143dbd.png)

**Comment by fabiospampinato** [comment]
Maybe you could replace this extension with this other one: https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-open-in-application

**Comment by kanlukasz** [comment]
Yes, that one is better a lot! thank you for the hint!
From my point of view, you should focus only on development of `Open in Application`,
because `Open in Browser` is basically almost the same. 
For me, case i closed
