### ISSUE TITLE
Open on specific port

### ISSUE THREAD

**Issue by SynapseUser** [fabiospampinato/vscode-open-in-browsers#6]
Hi -

First I would like to ask where do you put the settings for the mod ? I know you have shown some json formatted strings, but when I click on the settings - I am just given 1 line ? I did try enter some settings but  either I am putting them in the worng place or they are invalid. Either way they are gertting ingnored when I run the extension.

Is there a way to specify a port when launching a file in VSCode ? I have an apache server running on a local machine on a non-standard port and maybe at the same time set the root path for the server if necessary. 
I did try..
{  "port": 9000,   "pathMappings": {                 "C:\xampp\htdocs\pets": "${workspaceFolder}"             } }} }"

It would also be nice to specify an address for the server as well, so localhost, instead of file//

Ideally it would be perfect if you could launch it so it read..

http://localhost:portNumber/somefile.php

Many thanks,

Paul.

**Comment by fabiospampinato** [comment]
That kind of thing isn't supported by this extension. You can try this other extension to refresh the browser: https://github.com/fabiospampinato/vscode-browser-refresh but you'll still have to go to that address manually, unless you write a specific extension that can handle that.
