### ISSUE TITLE
Since V3.0, files are opened in default app instead browser

### ISSUE THREAD

**Issue by FreeHarry** [fabiospampinato/vscode-open-in-browsers#8]
Since the new version 3.0, files like markdown (*.md) or other types than html, are opened no more in the browser, but in the default application which is registered on the machine.

This is actually not what the function let expect. So it should open any file in browser as it did it in the past. Please can you revert to the old behavior.

**Comment by fabiospampinato** [comment]
The strings used for browsers changed in v3, now it's: "chrome", "firefox", "safari" or "edge".

Maybe you need to update your configuration? 🤔 What OS are you using?

**Comment by FreeHarry** [comment]
I'm using it on Windows/Linux.

It works with the new strings you mentioned. Thanks!

BUT: I also have 'Vivaldi' installed, and the old 'Internet Explorer' (for some purpose). It does NOT work with this browsers anymore.

Also, if some 'browser string' is not available, it should NOT open the default application. Because for example, if I want open a python file in browser, it tries to run it, which can lead to unexpected side effects. So, if a browser is not available it should maybe show an error message, BUT NOT use the default app.

**Comment by fabiospampinato** [comment]
Right, it should be fixed in v3.0.1 (it'll be visible on the marketplace in a bit), now unrecognized browser names will be used as is, so as long as you use the correct one (which is OS-dependent) it should work correctly, and if the browser is not found the default one should not be opened.

Thanks for the feedback 👍

**Comment by FreeHarry** [comment]
Thanks, works great now 🥇
